service: aws-node-express-api

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  express:
    handler: src/handler.index
    events:
      - httpApi: "*"
