service: aws-node-express-api

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  timeout: 29

functions:
  express:
    handler: src/handler.index
    events:
      - httpApi: "*"
