service: aws-node-express-api

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true

package:
  individually: true
  patterns:
    - "!src/**/*.spec.*"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"
