service: aws-node-express-api

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-apigw-binary

useDotenv: true

custom:
  apigwBinary:
    types:
      - "image/jpeg"
      - "text/csv"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  express:
    handler: src/handler.index
    events:
      - httpApi: "*"
